version: '3.8'

services:
  # ---------------- SERVIDORES ----------------
  server-1:
    image: rep-server:latest
    container_name: server-1
    ports: ["8081:8080"]
    environment:
      - SERVER_ID=server-1
      - SERVER_LIST=http://server-1:8080,http://server-2:8080,http://server-3:8080
      - START_DELAY=3

  server-2:
    image: rep-server:latest
    container_name: server-2
    ports: ["8082:8080"]
    environment:
      - SERVER_ID=server-2
      - SERVER_LIST=http://server-1:8080,http://server-2:8080,http://server-3:8080
      - START_DELAY=3

  server-3:
    image: rep-server:latest
    container_name: server-3
    ports: ["8083:8080"]
    environment:
      - SERVER_ID=server-3
      - SERVER_LIST=http://server-1:8080,http://server-2:8080,http://server-3:8080
      - START_DELAY=3

  # ---------------- CLIENTES ----------------
  client-1:
    image: rep-client:latest
    container_name: client-1
    environment:
      - CLIENT_ID=client-1
      - SERVER_LIST=http://server-1:8080,http://server-2:8080,http://server-3:8080
      - START_DELAY=8
    depends_on:
      - server-1
      - server-2
      - server-3

  client-2:
    image: rep-client:latest
    container_name: client-2
    environment:
      - CLIENT_ID=client-2
      - SERVER_LIST=http://server-1:8080,http://server-2:8080,http://server-3:8080
      - START_DELAY=8
    depends_on:
      - server-1
      - server-2
      - server-3

  client-3:
    image: rep-client:latest
    container_name: client-3
    environment:
      - CLIENT_ID=client-3
      - SERVER_LIST=http://server-1:8080,http://server-2:8080,http://server-3:8080
      - START_DELAY=8
    depends_on:
      - server-1
      - server-2
      - server-3