spring.application.name=rep-server

# Desliga o banner em texto (Spring ASCII Art)
spring.main.banner-mode=off

# Exibe apenas avisos e erros críticos do framework, ocultando os INFOs de inicialização
logging.level.root=WARN